---
apiVersion: v1
kind: Secret
metadata:
  name: pat-db-secret
  namespace: pat
type: Opaque
stringData:
  host: postgresql.pat-db.svc.cluster.local
  port: '5432'
  database: awx
  username: awx
  password: <password>
  sslmode: prefer
  type: unmanaged
