apiVersion: v1
kind: Secret
metadata:
  name: toweraccess
  namespace: ansible-automation-platform
type: Opaque
stringData:
  token: <token>
  host: https://controller-ansible-automation-platform.apps.comet.demolab.local
